# Generated by Django 4.2.28 on 2026-03-01 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WarningLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warning_type', models.CharField(choices=[('overdue', 'Overdue Notice'), ('reminder', 'Reminder'), ('final_notice', 'Final Notice'), ('policy_violation', 'Policy Violation'), ('general', 'General Warning')], default='general', max_length=30)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField(help_text='Body of the warning email.')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed')], default='pending', max_length=15)),
                ('sendgrid_message_id', models.CharField(blank=True, default='', max_length=255)),
                ('error_detail', models.TextField(blank=True, default='')),
                ('sent_by', models.CharField(blank=True, default='', help_text='Username of the staff member who triggered the warning.', max_length=150)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warnings', to='warnings_app.customer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
